[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "disco_server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "disco_core",
    "flask",
    "python-vlc",
    "pydantic",
    "flasgger",
    "SQLAlchemy",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.uv.sources]
disco_core = { path = "../disco_core", editable = true }

[tool.uv]
config-settings = { editable_mode = "compat" }

[tool.setuptools.packages.find]
where = ["."]
include = ["disco_server*"]
